name: Print Txt file


on:
  workflow_dispatch:


jobs: 
  print_txt_file:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: print content of the text file
        run: |
          cat habib.txt