name: Print Txt file


on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'Choose your server'
        required: true
        type: choice
        default: staging

        options: 
          - staging
          - production




jobs: 
  print_txt_file:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print User Input
        run: |
          echo "User input is: ${{ github.event.inputs.example_input }}"

      - name: print content of the text file
        run: |
          cat habib.txt